import Foundation
import SwiftUI

// This file defines a set of sane default colors
// for the theming system, based on the default
// "Apple Blue" accent color.


@_documentation(visibility: internal) //don't produce documentation for this type
public struct DefaultColors {
    public static let light_primary = Color(0xFF007AFF)
    public static let light_onPrimary = Color(0xFFFFFFFF)
    public static let light_primaryContainer = Color(0xFFD8E2FF)
    public static let light_onPrimaryContainer = Color(0xFF001A41)
    public static let light_secondary = Color(0xFFFF8400)
    public static let light_onSecondary = Color(0xFFFFFFFF)
    public static let light_secondaryContainer = Color(0xFFFFB784)
    public static let light_onSecondaryContainer = Color(0xFF000000)
    public static let light_tertiary = Color(0xFF00FBFF)
    public static let light_onTertiary = Color(0xFF000000)
    public static let light_tertiaryContainer = Color(0xFFB3FEFF)
    public static let light_onTertiaryContainer = Color(0xFF000000)
    public static let light_error = Color(0xFFBA1A1A)
    public static let light_errorContainer = Color(0xFFFFDAD6)
    public static let light_onError = Color(0xFFFFFFFF)
    public static let light_onErrorContainer = Color(0xFF410002)
    public static let light_surface = Color(0xFFFEFBFF)
    public static let light_surfaceContainerLow = Color(0xFFFFFFFF)
    public static let light_surfaceContainer = Color(0xFFECEDF9)
    public static let light_surfaceContainerHigh = Color(0xFFE0E2ED)
    public static let light_onSurface = Color(0xFF1B1B1F)
    public static let light_inverseSurface = Color(0xFF303033)
    public static let light_inverseOnSurface = Color(0xFFF2F0F4)
    public static let light_inversePrimary = Color(0xFFADC6FF)
    public static let light_outline = Color(0xFF74777F)
    public static let light_outlineVariant = Color(0xFFC4C6D0)
    public static let light_scrim = Color(0xFF000000)
    
    public static let dark_primary = Color(0xFF007AFF)
    public static let dark_onPrimary = Color(0xFFFFFFFF)
    public static let dark_primaryContainer = Color(0xFFADC6FF)
    public static let dark_onPrimaryContainer = Color(0xFF000000)
    public static let dark_secondary = Color(0xFFFF8400)
    public static let dark_onSecondary = Color(0xFFFFFFFF)
    public static let dark_secondaryContainer = Color(0xFFFFB886)
    public static let dark_onSecondaryContainer = Color(0xFF000000)
    public static let dark_tertiary = Color(0xFF00FBFF)
    public static let dark_onTertiary = Color(0xFF000000)
    public static let dark_tertiaryContainer = Color(0xFF00DCE0)
    public static let dark_onTertiaryContainer = Color(0xFF000000)
    public static let dark_error = Color(0xFFFF5353)
    public static let dark_onError = Color(0xFFFFFFFF)
    public static let dark_errorContainer = Color(0xFFFFB3AE)
    public static let dark_onErrorContainer = Color(0xFF000000)
    public static let dark_surface = Color(0xFF1B1B1F)
    public static let dark_surfaceContainerLow = Color(0xFF0B0E16)
    public static let dark_surfaceContainer = Color(0xFF31353D)
    public static let dark_surfaceContainerHigh = Color(0xFF494B52)
    public static let dark_onSurface = Color(0xFFE3E2E6)
    public static let dark_inverseSurface = Color(0xFFE3E2E6)
    public static let dark_inverseOnSurface = Color(0xFF1B1B1F)
    public static let dark_inversePrimary = Color(0xFF005BC1)
    public static let dark_outline = Color(0xFF8E9099)
    public static let dark_outlineVariant = Color(0xFF44474F)
    public static let dark_scrim = Color(0xFF000000)
}

#Preview("Light Colors") {
    ScrollView {
        VStack {
            ColorPreview(DefaultColors.light_primary, name: "light_primary", width: 300)
            ColorPreview(DefaultColors.light_onPrimary, name: "light_onPrimary", width: 300)
            ColorPreview(DefaultColors.light_primaryContainer, name: "light_primaryContainer", width: 300)
            ColorPreview(DefaultColors.light_onPrimaryContainer, name: "light_onPrimaryContainer", width: 300)
            ColorPreview(DefaultColors.light_secondary, name: "light_secondary", width: 300)
            ColorPreview(DefaultColors.light_onSecondary, name: "light_onSecondary", width: 300)
            ColorPreview(DefaultColors.light_secondaryContainer, name: "light_secondaryContainer", width: 300)
            ColorPreview(DefaultColors.light_onSecondaryContainer, name: "light_onSecondaryContainer", width: 300)
            ColorPreview(DefaultColors.light_tertiary, name: "light_tertiary", width: 300)
            ColorPreview(DefaultColors.light_onTertiary, name: "light_onTertiary", width: 300)
            ColorPreview(DefaultColors.light_tertiaryContainer, name: "light_tertiaryContainer", width: 300)
            ColorPreview(DefaultColors.light_onTertiaryContainer, name: "light_onTertiaryContainer", width: 300)
            ColorPreview(DefaultColors.light_error, name: "light_error", width: 300)
            ColorPreview(DefaultColors.light_onError, name: "light_onError", width: 300)
            ColorPreview(DefaultColors.light_errorContainer, name: "light_errorContainer", width: 300)
            ColorPreview(DefaultColors.light_onErrorContainer, name: "light_onErrorContainer", width: 300)
            ColorPreview(DefaultColors.light_surface, name: "light_surface", width: 300)
            ColorPreview(DefaultColors.light_surfaceContainerLow, name: "light_surfaceContainerLow", width: 300)
            ColorPreview(DefaultColors.light_surfaceContainer, name: "light_surfaceContainer", width: 300)
            ColorPreview(DefaultColors.light_surfaceContainerHigh, name: "light_surfaceContainerHigh", width: 300)
            ColorPreview(DefaultColors.light_onSurface, name: "light_onSurface", width: 300)
            ColorPreview(DefaultColors.light_inverseSurface, name: "light_inverseSurface", width: 300)
            ColorPreview(DefaultColors.light_inverseOnSurface, name: "light_inverseOnSurface", width: 300)
            ColorPreview(DefaultColors.light_inversePrimary, name: "light_inversePrimary", width: 300)
            ColorPreview(DefaultColors.light_outline, name: "light_outline", width: 300)
            ColorPreview(DefaultColors.light_outlineVariant, name: "light_outlineVariant", width: 300)
            ColorPreview(DefaultColors.light_scrim, name: "light_scrim", width: 300)
        }.frame(maxWidth: .infinity)
    }
}

#Preview("Dark Colors") {
    ScrollView {
        VStack {
            ColorPreview(DefaultColors.dark_primary, name: "dark_primary", width: 300)
            ColorPreview(DefaultColors.dark_onPrimary, name: "dark_onPrimary", width: 300)
            ColorPreview(DefaultColors.dark_primaryContainer, name: "dark_primaryContainer", width: 300)
            ColorPreview(DefaultColors.dark_onPrimaryContainer, name: "dark_onPrimaryContainer", width: 300)
            ColorPreview(DefaultColors.dark_secondary, name: "dark_secondary", width: 300)
            ColorPreview(DefaultColors.dark_onSecondary, name: "dark_onSecondary", width: 300)
            ColorPreview(DefaultColors.dark_secondaryContainer, name: "dark_secondaryContainer", width: 300)
            ColorPreview(DefaultColors.dark_onSecondaryContainer, name: "dark_onSecondaryContainer", width: 300)
            ColorPreview(DefaultColors.dark_tertiary, name: "dark_tertiary", width: 300)
            ColorPreview(DefaultColors.dark_onTertiary, name: "dark_onTertiary", width: 300)
            ColorPreview(DefaultColors.dark_tertiaryContainer, name: "dark_tertiaryContainer", width: 300)
            ColorPreview(DefaultColors.dark_onTertiaryContainer, name: "dark_onTertiaryContainer", width: 300)
            ColorPreview(DefaultColors.dark_error, name: "dark_error", width: 300)
            ColorPreview(DefaultColors.dark_onError, name: "dark_onError", width: 300)
            ColorPreview(DefaultColors.dark_errorContainer, name: "dark_errorContainer", width: 300)
            ColorPreview(DefaultColors.dark_onErrorContainer, name: "dark_onErrorContainer", width: 300)
            ColorPreview(DefaultColors.dark_surface, name: "dark_surface", width: 300)
            ColorPreview(DefaultColors.dark_onSurface, name: "dark_onSurface", width: 300)
            ColorPreview(DefaultColors.dark_inverseSurface, name: "dark_inverseSurface", width: 300)
            ColorPreview(DefaultColors.dark_inverseOnSurface, name: "dark_inverseOnSurface", width: 300)
            ColorPreview(DefaultColors.dark_inversePrimary, name: "dark_inversePrimary", width: 300)
            ColorPreview(DefaultColors.dark_outline, name: "dark_outline", width: 300)
            ColorPreview(DefaultColors.dark_outlineVariant, name: "dark_outlineVariant", width: 300)
            ColorPreview(DefaultColors.dark_scrim, name: "dark_scrim", width: 300)
        }
        .frame(maxWidth: .infinity)
        .background(.black)
    }
}
