#if os(iOS)

import Foundation
import SwiftUI

// This file defines a set of sane default colors
// for the theming system, based on the default
// "Apple Blue" accent color.

public let default_light_primary = Color(0xFF007AFF)
public let default_light_onPrimary = Color(0xFFFFFFFF)
public let default_light_primaryContainer = Color(0xFFD8E2FF)
public let default_light_onPrimaryContainer = Color(0xFF001A41)
public let default_light_secondary = Color(0xFFFF8400)
public let default_light_onSecondary = Color(0xFFFFFFFF)
public let default_light_secondaryContainer = Color(0xFFFFB784)
public let default_light_onSecondaryContainer = Color(0xFF000000)
public let default_light_tertiary = Color(0xFF00FBFF)
public let default_light_onTertiary = Color(0xFF000000)
public let default_light_tertiaryContainer = Color(0xFFB3FEFF)
public let default_light_onTertiaryContainer = Color(0xFF000000)
public let default_light_error = Color(0xFFBA1A1A)
public let default_light_errorContainer = Color(0xFFFFDAD6)
public let default_light_onError = Color(0xFFFFFFFF)
public let default_light_onErrorContainer = Color(0xFF410002)
public let default_light_surface = Color(0xFFFEFBFF)
public let default_light_surfaceContainerLow = Color(0xFFFFFFFF)
public let default_light_surfaceContainer = Color(0xFFECEDF9)
public let default_light_surfaceContainerHigh = Color(0xFFE0E2ED)
public let default_light_onSurface = Color(0xFF1B1B1F)
public let default_light_inverseSurface = Color(0xFF303033)
public let default_light_inverseOnSurface = Color(0xFFF2F0F4)
public let default_light_inversePrimary = Color(0xFFADC6FF)
public let default_light_outline = Color(0xFF74777F)
public let default_light_outlineVariant = Color(0xFFC4C6D0)
public let default_light_scrim = Color(0xFF000000)

public let default_dark_primary = Color(0xFF007AFF)
public let default_dark_onPrimary = Color(0xFFFFFFFF)
public let default_dark_primaryContainer = Color(0xFFADC6FF)
public let default_dark_onPrimaryContainer = Color(0xFF000000)
public let default_dark_secondary = Color(0xFFFF8400)
public let default_dark_onSecondary = Color(0xFFFFFFFF)
public let default_dark_secondaryContainer = Color(0xFFFFB886)
public let default_dark_onSecondaryContainer = Color(0xFF000000)
public let default_dark_tertiary = Color(0xFF00FBFF)
public let default_dark_onTertiary = Color(0xFF000000)
public let default_dark_tertiaryContainer = Color(0xFF00DCE0)
public let default_dark_onTertiaryContainer = Color(0xFF000000)
public let default_dark_error = Color(0xFFFF5353)
public let default_dark_onError = Color(0xFFFFFFFF)
public let default_dark_errorContainer = Color(0xFFFFB3AE)
public let default_dark_onErrorContainer = Color(0xFF000000)
public let default_dark_surface = Color(0xFF1B1B1F)
public let default_dark_surfaceContainerLow = Color(0xFF0B0E16)
public let default_dark_surfaceContainer = Color(0xFF31353D)
public let default_dark_surfaceContainerHigh = Color(0xFF494B52)
public let default_dark_onSurface = Color(0xFFE3E2E6)
public let default_dark_inverseSurface = Color(0xFFE3E2E6)
public let default_dark_inverseOnSurface = Color(0xFF1B1B1F)
public let default_dark_inversePrimary = Color(0xFF005BC1)
public let default_dark_outline = Color(0xFF8E9099)
public let default_dark_outlineVariant = Color(0xFF44474F)
public let default_dark_scrim = Color(0xFF000000)


#Preview("Light Colors") {
    ScrollView {
        VStack {
            ColorPreview(default_light_primary, name: "default_light_primary", width: 300)
            ColorPreview(default_light_onPrimary, name: "default_light_onPrimary", width: 300)
            ColorPreview(default_light_primaryContainer, name: "default_light_primaryContainer", width: 300)
            ColorPreview(default_light_onPrimaryContainer, name: "default_light_onPrimaryContainer", width: 300)
            ColorPreview(default_light_secondary, name: "default_light_secondary", width: 300)
            ColorPreview(default_light_onSecondary, name: "default_light_onSecondary", width: 300)
            ColorPreview(default_light_secondaryContainer, name: "default_light_secondaryContainer", width: 300)
            ColorPreview(default_light_onSecondaryContainer, name: "default_light_onSecondaryContainer", width: 300)
            ColorPreview(default_light_tertiary, name: "default_light_tertiary", width: 300)
            ColorPreview(default_light_onTertiary, name: "default_light_onTertiary", width: 300)
            ColorPreview(default_light_tertiaryContainer, name: "default_light_tertiaryContainer", width: 300)
            ColorPreview(default_light_onTertiaryContainer, name: "default_light_onTertiaryContainer", width: 300)
            ColorPreview(default_light_error, name: "default_light_error", width: 300)
            ColorPreview(default_light_onError, name: "default_light_onError", width: 300)
            ColorPreview(default_light_errorContainer, name: "default_light_errorContainer", width: 300)
            ColorPreview(default_light_onErrorContainer, name: "default_light_onErrorContainer", width: 300)
            ColorPreview(default_light_surface, name: "default_light_surface", width: 300)
            ColorPreview(default_light_surfaceContainerLow, name: "default_light_surfaceContainerLow", width: 300)
            ColorPreview(default_light_surfaceContainer, name: "default_light_surfaceContainer", width: 300)
            ColorPreview(default_light_surfaceContainerHigh, name: "default_light_surfaceContainerHigh", width: 300)
            ColorPreview(default_light_onSurface, name: "default_light_onSurface", width: 300)
            ColorPreview(default_light_inverseSurface, name: "default_light_inverseSurface", width: 300)
            ColorPreview(default_light_inverseOnSurface, name: "default_light_inverseOnSurface", width: 300)
            ColorPreview(default_light_inversePrimary, name: "default_light_inversePrimary", width: 300)
            ColorPreview(default_light_outline, name: "default_light_outline", width: 300)
            ColorPreview(default_light_outlineVariant, name: "default_light_outlineVariant", width: 300)
            ColorPreview(default_light_scrim, name: "default_light_scrim", width: 300)
        }.frame(maxWidth: .infinity)
    }
}

#Preview("Dark Colors") {
    ScrollView {
        VStack {
            ColorPreview(default_dark_primary, name: "default_dark_primary", width: 300)
            ColorPreview(default_dark_onPrimary, name: "default_dark_onPrimary", width: 300)
            ColorPreview(default_dark_primaryContainer, name: "default_dark_primaryContainer", width: 300)
            ColorPreview(default_dark_onPrimaryContainer, name: "default_dark_onPrimaryContainer", width: 300)
            ColorPreview(default_dark_secondary, name: "default_dark_secondary", width: 300)
            ColorPreview(default_dark_onSecondary, name: "default_dark_onSecondary", width: 300)
            ColorPreview(default_dark_secondaryContainer, name: "default_dark_secondaryContainer", width: 300)
            ColorPreview(default_dark_onSecondaryContainer, name: "default_dark_onSecondaryContainer", width: 300)
            ColorPreview(default_dark_tertiary, name: "default_dark_tertiary", width: 300)
            ColorPreview(default_dark_onTertiary, name: "default_dark_onTertiary", width: 300)
            ColorPreview(default_dark_tertiaryContainer, name: "default_dark_tertiaryContainer", width: 300)
            ColorPreview(default_dark_onTertiaryContainer, name: "default_dark_onTertiaryContainer", width: 300)
            ColorPreview(default_dark_error, name: "default_dark_error", width: 300)
            ColorPreview(default_dark_onError, name: "default_dark_onError", width: 300)
            ColorPreview(default_dark_errorContainer, name: "default_dark_errorContainer", width: 300)
            ColorPreview(default_dark_onErrorContainer, name: "default_dark_onErrorContainer", width: 300)
            ColorPreview(default_dark_surface, name: "default_dark_surface", width: 300)
            ColorPreview(default_dark_onSurface, name: "default_dark_onSurface", width: 300)
            ColorPreview(default_dark_inverseSurface, name: "default_dark_inverseSurface", width: 300)
            ColorPreview(default_dark_inverseOnSurface, name: "default_dark_inverseOnSurface", width: 300)
            ColorPreview(default_dark_inversePrimary, name: "default_dark_inversePrimary", width: 300)
            ColorPreview(default_dark_outline, name: "default_dark_outline", width: 300)
            ColorPreview(default_dark_outlineVariant, name: "default_dark_outlineVariant", width: 300)
            ColorPreview(default_dark_scrim, name: "default_dark_scrim", width: 300)
        }
        .frame(maxWidth: .infinity)
        .background(.black)
    }
}

#endif
